services:
  agrisistance-land-db:
    image: postgres:latest
    restart: always
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_LAND_DB}
    networks:
      - agrisistance-network

  agrisistance-user-db:
    image: postgres:latest
    restart: always
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_USER_DB}
    networks:
      - agrisistance-network

  agrisistance-network-db:
    image: postgres:latest
    restart: always
    ports:
      - "5436:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_NETWORK_DB}
    networks:
      - agrisistance-network

  agrisistance-redis-cache:
    image: redis:latest
    restart: always
    ports:
      - "6380:6379"
    networks:
      - agrisistance-network

networks:
  agrisistance-network:
    driver: bridge
