services:
  agrisistance-db:
    image: postgres:16
    restart: always
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - agrisistance-network

networks:
  agrisistance-network:
    driver: bridge
